mqtt:
  host: nas
ffmpeg:
  # Optional: global ffmpeg args (default: shown below)
  global_args: -hide_banner -loglevel warning
  # Optional: global hwaccel args (default: shown below)
  # NOTE: See hardware acceleration docs for your specific device
  hwaccel_args: []
  # Optional: global input args (default: shown below)
  input_args: -avoid_negative_ts make_zero -fflags +genpts+discardcorrupt -rtsp_transport tcp -stimeout 5000000 -use_wallclock_as_timestamps 1
  # Optional: global output args
  output_args:
    # Optional: output args for detect streams (default: shown below)
    detect: -f rawvideo -pix_fmt yuv420p
    # Optional: output args for record streams (default: shown below)
    record: -f segment -segment_time 60 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c copy
    # Optional: output args for rtmp streams (default: shown below)
    rtmp: -c copy -f flv
  
cameras:
  voordeur:
    zones:
      betonpad:
        coordinates: 829,1307,1296,1245,1538,1157,1538,1226,1362,1310,1113,1380,893,1417,556,1448,352,1450,0,1386,0,1286,321,1320
      padje:
        coordinates: 907,1418,1055,1534,1442,1768,1273,1845,989,1965,670,1995,610,1778,575,1590,559,1447
    mqtt:
     timestamp: True
     bounding_box: False
     crop: True
     height: 500
     # Optional: Restrict mqtt messages to objects that entered any of the listed zones (default: no required zones)
     required_zones: [padje]
    ffmpeg:
      inputs:
        - path: rtsp://admin:{FRIGATE_RTSP_PASSWORD}@e52294209.lan:554
          roles:
            - detect
            - rtmp
            - record
    motion:
      mask:
        - 0,686,69,519,330,516,664,605,780,953,712,1050,0,1179
        - 647,1927,647,1975,60,1976,61,1928
        - 0,0,1538,0,1536,1009,1154,1008,932,1015,929,975,688,901,478,894,448,952,391,942,360,972,0,965
snapshots:
      enabled: True

record:
      enabled: True
      retain_days: 600
      events:
              pre_capture: 5
              post_capture: 5
              objects:
                      - person

detect:
        width: 1536
        height: 2048
        #    width: 768
        #    height: 1024
        fps: 5

objects:
 track:
  - person
  - car
  - bicycle
  - dog

detectors:
  cpu1:
    type: cpu
  cpu2:
    type: cpu
